== Subject

The subject of this Engineering Report (ER) is a hackathon event that was held from June 20th to 21st, 2019 to advance the development of OGC Application Programming Interface (API) specifications. An API is a standard set of documented and supported functions and procedures that expose the capabilities or data of an operating system, application or service to other applications (adapted from ISO/IEC TR 13066-2:2016). The OGC API Hackathon 2019, as the event was called, was hosted by the Geovation Hub in London, United Kingdom. The event was sponsored by the European Space Agency (ESA) and the Ordnance Survey.

== Executive Summary

(( The following is, as all texts in double square brackets, a helper text. Please remove this and all other helper texts once done. ))

(( The Executive Summary clause shall contain the key findings and results in a concise form. A more detailed description of the findings should be in the body of the report. ))

(( The Executive Summary shall contain a business value statement that should describe the value of this Engineering Report to improve interoperability, advance location-based technologies or realize innovations. ))

(( This section shall include precise descriptions of the requirements that have been addressed by the work documented in this Engineering Report; together with the research motivation that answers the fundamental question: What motivated us to address this topic in this report? ))

(( This section provides an overview of recommendations on how to further proceed with the achievements documented in this ER. ))

(( This section shall be between 1-3 pages.))

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
|Name |Organization | Role
|Gobe Hobona | Open Geospatial Consortium |TBA
|Scott Simmons | Open Geospatial Consortium |TBA
|Michael Gordon | Ordnance Survey |TBA
|Simon Green | Ordnance Survey |TBA
|Clemens Portele | interactive instruments GmbH |TBA
|Jorge Samuel Mendes de Jesus | ISRIC - World Soil Information |TBA
|Peter Baumann | rasdaman GmbH |TBA
|Francesco	Bartoli | Geobeyond |TBA
|Dirk Stenger | lat/lon GmbH |TBA
|Chuck Heazel | Heazeltech LLC |TBA
|Matthias Mohr | University of Münster |TBA
|Robin Houtmeyers | Hexagon Geospatial |TBA
|TBA | TBA |TBA
|TBA | TBA |TBA
|TBA | TBA |TBA
|====================

NOTE: Role = Editor and/or Contributor

// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
