== Terms and definitions



For the purposes of this report, the definitions specified in Clause 4 of the OWS Common Implementation Standard https://portal.opengeospatial.org/files/?artifact_id=38867&version=2[OGC 06-121r9] shall apply. In addition, the following terms and definitions apply.

.NOTE: Delete the first three terms because they are examples.

&#9679; application programming interface ::

 standard set of documented and supported functions and procedures that expose the capabilities or data of an operating system, application or service to other applications (adapted from ISO/IEC TR 13066-2:2016)

&#9679; portrayal ::

 presentation of information to humans (source: ISO 19117)

&#9679; term name ::

 text of the definition

&#9679; term name|synonym  ::

 text of the definition


===	Abbreviated terms

.NOTE: The abbreviated terms clause gives a list of the abbreviated terms and the symbols necessary for understanding this document. All symbols should be listed in alphabetical order. Some more frequently used abbreviated terms are provided below as examples.

* API	Application Programming Interface
* WCS	Web Coverage Service
* WFS	Web Feature Service
* WMTS	Web Map Tile Service
* OWS	OGC Web Services
