[[OGCAPISpecifications]]
== OGC API Specifications

This chapter describes each of the OGC API specifications that were advanced by the Hackathon. The section presents an overview of each specification and is not intended to be a substitute for reading the complete specification.

=== OGC API - Common

The OGC API - Common specification documents the set of common practices and shared requirements that have emerged from the development of Resource Oriented Architectures and Web APIs within the OGC. The specification serves as a common foundation upon which all OGC APIs will be built. As such, the OGC API - Common standard serves as the "OWS Common" standard for OGC Resource Oriented APIs. Consistent with the architecture of the Web, this specification uses a resource architecture that conforms to principles of Representational State Transfer (REST). The specification establishes a common pattern that is based on https://www.openapis.org/[OpenAPI].

In addition to identifying core resources, the OGC API - Common specification goes on to specify HTTP status codes that may be supported by an OGC API, as well as how to handle web caching, coordinate reference systems and encodings. The specification also describes how to handle common parameters such as bounding boxes and date-time constraints.

The following subsection presents a summary of the core resources.


==== Key Resources

A summary of the paths offered by the OGC API - Common specification are shown below:

* Path = /
** Returns landing page
* Path = /api
** Returns API Description document (OpenAPI)
* Path = /conformance
** Returns a set of conformance class URIs.
* Path = /collections
** Returns metadata describing the collections accessible through this API
* Path = /collections/{collectionId}
**Returns metadata describing the collection identified by {collectionId}
*Path = /collections/{collectionId}/items
** Returns --- TBD.  This may be where Common leaves off and resource specific standards take over.



=== OGC API - Features

The OGC API - Features specification offers the capability to create, modify and query spatial data on the Web. The specification is a multi-part document. The Core part of the specification describes the mandatory capabilities that every implementing service has to support and is restricted to read-access to spatial data. Additional capabilities that address specific needs will be specified in additional parts. Envisaged future capabilities include, for example, support for creating and modifying data, more complex data models, richer queries, and additional coordinate reference systems. This specification builds on the Web Feature Service (WFS) standard.

==== Key Resources

TBA

=== OGC API - Processes

The OGC API - Processes specification provides defines how a client application can request the execution of a process, how the inputs to that process can be provided, and how the output from the process is handled. The specification allows for the wrapping of computational tasks into an executable process that can be invoked by a client application. Examples of computational processes that can be supported by implementations of this specification include raster algebra, geometry buffering, constructive area geometry, routing and several others. This specification builds on the Web Processing Service (WPS) standard.

==== Key Resources

TBA

=== OGC API - Map Tiles

The OGC API - Map Tiles specification defines an OGC standard for a Web Map Tile API that can serve map tiles of spatially referenced data using tile images with predefined content, extent, and resolution. The specification describes the discovery and query operations of an API that provides access to Map Tiles in a manner independent of the underlying data store. The discovery operations allow the API to be interrogated to determine its capabilities and retrieve metadata about the organisation and distribution of tiles. The query operations allow tiles to be retrieved from the underlying data store based upon simple selection criteria, defined by the client. This specification builds on the Web Map Tile Service (WMTS) standard.

==== Key Resources

TBA

=== OGC API - Coverages

The OGC API - Coverages specification defines a Web API for accessing coverages that are modelled according to the http://docs.opengeospatial.org/is/09-146r6/09-146r6.html[Coverage Implementation Schema (CIS) 1.1]. Coverages are represented by some binary or ASCII serialization, specified by some data (en­coding) format. Arguably the most popular type of coverage is that of a gridded coverage. Gridded coverages have a grid as their domain set describing the direct positions in multi-dimensional coordinate space, depending on the type of grid. Satellite imagery is typically modelled as a gridded coverage, for example. The OGC API - Coverages specification builds on the Web Coverage Service (WCS) standard.


==== Key Resources

A summary of the paths offered by the OGC API - Coverages specification are shown below:

* From Common
** Path = /,
** Path = /api,
** Path = /conformance
** Path = /collections/
** Path = /collections/{collectionId}
* Path = /collections/{collectionId}/coverages
** Returns metadata about each coverage in the collection
* Path = /collections/{collectionId}/coverages/{coverageID}
** Returns the coverage itself.  Typically as an image file.
* Path = /collections/{collectionId}/coverages/{coverageID}/metadata
** Returns metadata about a coverage.
* Path = /collections/{collectionId}/coverages/{coverageID}/domainset
** Returns a description of the domain set of the coverage
* Path = /collections/{collectionId}/coverages/{coverageID}/rangetype
** Returns a description of the range type of the coverage
