[[KeyFindings]]
== Key Findings

TBA

=== Results


==== Processes

The participants made an observation that some attributes for referenceValue were missing. As a result, changes were made to add attributes for identifying the MIME type, schema and encoding in a referenceValue object. These changes were needed for providing input in a specific format or returning output in a specific format.

There was a https://github.com/opengeospatial/wps-rest-binding/issues/42[suggestion] to add ows:additionalProperties and ows:context to metadata. It was observed that ows:additionalParameters allows a service to provide key value pairs metadata information. It was also observed that Testbed 13 and testbed 14 had demonstrated the utility of such a capability. As a result, the hackathon participants committed changes to the OGC API - Process specification adding the definition of additionalParameters.

There was a https://github.com/opengeospatial/wps-rest-binding/issues/37[discussion] about whether process output arrays are fully supported. The participants observed that currently the http://www.opengis.net/spec/WPS/2.0/req/conceptual-model/process/output-value-cardinality[output-value-cardinality] requirement limits cardinality of the output to one. A number of workarounds were suggested including returning a list of outputs, returning an archive (zip), returning a Metalink, or returning Multipart/mixed responses. The participants concluded that a solution would need to handle all kind of outputs, including outputs by reference, as well as binary files.


There was a https://github.com/opengeospatial/wps-rest-binding/issues/30[discussion] about how to specify synchronous execution OGC API Hackathon. The options identified included i) Either use a query parameter or a HTTP header to specify the execution mode, ii) Return a result object, iii)  Do not return a header with the location (as there technically is no location, i.e. its a temp. This issue was also related to the broader issue of how to choose between synchronous and asynchronous mode for job creation. The participants observed that indeed the WPS 2.0 specification has a jobID in the the status object, and therefore the OGC API - Processes specification should also include a jobID into the statusInfo object.

There was a https://github.com/opengeospatial/wps-rest-binding/issues/31[suggestion] for an extension supporting triggers according to job status. In particular the suggestion was for the user/client to be able to specify triggers for conditions like: `onSuccess` a Url to be triggered upon process completion, or `onFail` a URL to be triggered on process failure, `progressUpdate` a URL to be triggered by the job while progressing and should contain progress status (eg. proccent of job completion). Participants considered whether such a capability might be more appropriate as an extension, perhaps associated with a pub/sub notification capability.

There was a https://github.com/opengeospatial/wps-rest-binding/issues/32[suggestion] to add the exception information to the status information at GET `/processes/{id}/jobs/{jobID}` and remove the GET `/processes/{id}/jobs/{jobID}/exception` endpoint. The participants considered whether an HTTP 201 code should be returned with POST /processes/{id}/jobs. The participants resolved that allowing for plural form results could address this issue, for example `processes/{processId}/jobs/{jobId}/results/{resultId}`. Use of an HTTP 201 code was however inconclusive.


==== Map Tiles

The participants identified three roots for API building blocks, namely the root of the service, collection ID, and collection ID combined the coverage ID. A need to combine these root paths with maps and tiles was identified. There was an observation made that if the roots are combined with maps and tiles, there is an opportunity to provide much more information through data tiles such as vector tiles or coverage tiles. There was also an observation made that if a style and style id are concatenated with the path then the API would be able to combine data tiles with portrayals of the information. There was a third alternative identified, which is the concatenation of both the aforementioned approaches.

These paths have associated with them specific query parameters. Participants observed that such a capability may not be fully supported by OpenAPI 3.0.

There was a discussion about whether the response for maps should return raster or vector maps. Related to this was whether a map was at the same level as a collection. There was agreement that maps are not at the same level as collections.

==== Coverage

Notes to be rephrased:
* Decided to stick with coverages
* For each axis, have a separate coverage filter.
* Concluded that we do not have a construct in the core that supports filtering coverages.
* Want to inherit from Common as much as possible.
* Agreed not to include the complete coverage description.
* We want to inherit the bbox and time parameter from Common.
* We have different ways for getting the coverages individually. Since not every format is suitable for transferring all of the coverage information, there needs to be different ways for getting the different types of coverages.
* For applications that do not want to use collections, they can just use coverages/coverageid

There was a discussion about whether parameters, values and URL bases were case sensitive. This issue was observed to be applicable to all of the specifications. There was a suggestion that the Common spec should specify a rule for case sensitivity and that that rule should be consistent with the RFC.

==== Common

There was a discussion about whether OGC API - Common should support the CRS:84 coordinate system (WGS84) by default. The participants observed that the collectionInfo metadata (returned for each collection) allows one to specify the CRS supported by the collection. The client can specify one of the other CRS if they do not support the default. For coverages, the default CRS was observed to be the native CRS. The participants concluded that there will be a default CRS for the API and the OGC API - Common specification should have complete control over the CRS and the default CRS should not constrain the resource.

The participants observed that there is a need for something like CRS:84 that has ellipsoid height. EPSG:4327 was suggested as a possible basis for such a CRS, with the caveat that it has been deprecated.

==== Technology Integration Experiments (TIE)

The following table presents Technology Integration Experiments (TIE) that were completed during the Hackathon.

[#table_ties,reftext='{table-caption} {counter:table-num}']
.Technology Integration Experiments (TIE) for OGC APIs
[cols=",,,,",width="75%",options="header",align="center"]
|===
|Server/Client | Hexagon | Helyx | OpenSphere | Esri

|52 North |  | Processes  | |

|CubeWerx |  | Processes |  |

|Esri | Map Tiles |   |   | Map Tiles

|Helyx |  | Processes  |  |

|pygeoapi |  |  | Features |

|geoserver |  |   | Features |

|spacebel |  |   | Features |

|===


=== Alternatives

TBA

=== Experiences

TBA

=== Lessons learnt

TBA

=== What occurred

TBA

=== What are the next steps?

TBA
