# -*- coding: UTF-8 -*-
f = open("orgs.txt", "r")
for x in f:
  outfile = (str(x).replace(" ","").replace(",","").replace("-","").replace(".","").replace("/","").replace("°",""))
  outfile = outfile.strip()
  f = open("participanting-organizations/"+outfile+".adoc", "w")
  f.write('[['+outfile+']]\n')
  f.write('=== '+x+'\n\n')
  f.write('\nTBA'+'\n\n')
  f.write('==== Motivation to Participate'+'\n')
  f.write('\nTBA'+'\n\n')
  f.write('==== Implemented Solution'+'\n')
  f.write('\nTBA'+'\n\n')
  f.write('==== Proposed Alternatives'+'\n')
  f.write('\nTBA'+'\n\n')
  f.write('==== Experiences with OGC API Specifications'+'\n')
  f.write('\nTBA'+'\n\n')
  f.write('==== Other Impressions & Recommendations'+'\n')
  f.write('\nTBA'+'\n\n')
  f.close()
